name: Deploy Site
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - run: npm run deploy
      env:
        GIT_USER: ${{ secrets.GITHUB_TOKEN }}
